### ISSUE TITLE
Проверить ДЗ тесты

### ISSUE THREAD

**Issue by AIRAT1** [AIRAT1/taxi-service#6]
Не могу понять почему покрытие тестами в сервис классе только 87% и как это пофиксить. Зелёным светится зона внутри блока if, но сам блок if помечен жёлтым.

**Comment by AIRAT1** [comment]
100% test coverage achieved

**Comment by coursar** [comment]
Значит не все бранчи прошли: если условие одно, то должен быть код на прохождение условия и не прохождение
